import { createSlice } from "@reduxjs/toolkit";

// Initial state for the favorite items
const initialState = {
  favoriteItems: [], // Array to store favorite items
};

// Create a slice for the favorite reducer
const favoriteSlice = createSlice({
  name: "favorite",
  initialState,
  reducers: {
    // Add item to favorites
    addToFavorites(state, action) {
      const newItem = action.payload;
      state.favoriteItems.push(newItem);
    },
    // Remove item from favorites
    removeFromFavorites(state, action) {
      const itemIdToRemove = action.payload?.itemIdToRemove;
      state.favoriteItems = state.favoriteItems.filter(
        (item) => item.id !== itemIdToRemove
      );
    },
  },
});

// Export actions generated by the favorite slice
export const { addToFavorites, removeFromFavorites } = favoriteSlice.actions;

// Export the reducer function
export default favoriteSlice.reducer;
